version: '3.4'

services:
  mssql:
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Password!1234
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      
  ef.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__MSSQL=Server=mssql;Database=MyEF;User Id=sa;Password=Password!1234;Persist Security Info=False;Encrypt=False;
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
