version: '3.4'

services:
  mssql:
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Password!1234
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes:
      - sqlvolume:/var/opt/mssql
      
  ef.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
