version: '3.4'

services:
  grafana:
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'

  prometheus:
    container_name: prometheus
    ports:
      - "9090:9090"

  challenges.api:
    container_name: challenges.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro