name: Test

on:
  push:
    branches: [ "EntityFramework" ]
  pull_request:
    branches: [ "EntityFramework" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore --no-build
    - name: Build
      run: dotnet build --no-restore
